name: blank
on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'cluster name'
        required: true

jobs:
  process_jira_payload:
    runs-on: ubuntu-latest
    steps:
      - name: Print Jira Payload
        env:
          JIRA_PAYLOAD: ${{ inputs.cluster }}
        run: |
          echo "Received payload: $JIRA_PAYLOAD"
