name: blank
on:
  workflow_dispatch:
    types: [jira-event]

jobs:
  process_jira_payload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print Jira Payload
        env:
          JIRA_PAYLOAD: ${{ toJson(github.event.client_payload) }}
        run: |
          echo "Received payload: $JIRA_PAYLOAD"
